http://localhost:4000/

###
http://localhost:4000/status

###
http://localhost:4000/blocks

###
POST http://localhost:4000/blocks

{
    "message": "Data for my block"
}

###
http://localhost:4000/blocks/7546a32b685b12dff966766b344d60d2c335d6051218502ce13c8a3cc397ace5